M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Mo 13 Nov 2023 10:42:32 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-13T10:42:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X202.6Y-86.46
T2
X176.85Y-59.3
X176.85Y-108.3
X234.85Y-59.3
X234.85Y-108.3
T0
M30
