M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fri 22 Dec 2023 20:45:26 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-22T20:45:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X166.38Y-71.24
T2
X97.5Y-114.5
X97.5Y-189.5
X172.5Y-114.5
X172.5Y-189.5
T0
M30
