M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Mo 23 Okt 2023 09:56:06 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-23T09:56:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X190.834Y-71.872
T2
X176.85Y-59.3
X176.85Y-108.3
X209.5Y-107.0
X234.85Y-59.3
X234.85Y-108.3
X254.5Y-62.0
T0
M30
